config/routes.rb
Store::Application.routes.draw do
  resources :authentications

  resources :roles

  devise_for :users

  resources :categories

  resources :products

  root :to =>'products#index'

  match '/auth/:provider/callback' => 'authentications#create'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  #attr_accessible :user_id, :provider, :uid
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to  :category
  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  validates :image_url, :format => {
      :with => %r{\.(gif|jpg|png)$}i,
      :message => 'must be a URL for GIF, JPG or PNG image.'
  }

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :role
  has_many :authentications
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end

  def create
      auth = request.env["omniauth.auth"]
      current_user.authentications.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.search(params[:search])

    #creamos una instancia de producto para que la vista pueda tener modal
    @product = Product.new
    @formName = 'products'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
      format.js
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/authentications/index.html.erb
<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
  </tr>
  <% for authentication in @authentications %>
    <tr>
      <td><%= authentication.user_id %></td>
      <td><%= authentication.provider %></td>
      <td><%= authentication.uid %></td>
      <td><%= link_to "Destroy", authentication, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="user_nav" style="padding-top: 30px">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="clearfix">
    <%= f.label :title %>
    <div class="input">
    <%= f.text_field :title %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :category_id %>
    <div class="input">
    <%=f.collection_select :category_id, Category.all, :id, :name  %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :description %>
    <div class="input">
    <%= f.text_area :description,:rows=>10 %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :image_url %>
    <div class="input">
    <%= f.text_field :image_url %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :price %>
    <div class="input">
    <%= f.text_field :price %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit :class => 'btn info'%>
  </div>
<% end %>

app/views/products/_modal_form.html.erb
<div id="modal-form-<%= @formName%>" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3><%= @formName.upcase%></h3>
  </div>
  <div id="<%= @formName%>-form">
    <%= render :partial => @formName+"/form" %>
  </div>
</div>

app/views/products/_product_tpl.html.erb
<div class="span5">
  <%= image_tag('http://placehold.it/90x90', :class => 'thumbnail') %>
  <h2><%= @product.title %></h2>
  <p><%= sanitize @product.description %></p>
  <p><span class="label notice"><%= number_to_currency(@product.price) %></span></p>
</div>

app/views/products/_products.html.erb
 <table class="bordered-table zebra-striped" data-sortable="true">
      <thead>
      <tr>
        <th class="no-border"></th>
        <th class="no-border"></th>
        <th class="no-border"></th>
        <th class="no-border">
          <button data-controls-modal="modal-form-<%= @formName %>" data-backdrop="false" data-keyboard="true" class="btn"
                  onclick="$('#products-form').html(' ').load('<%= new_product_path%>');">Add Product
          </button>
        </th>
      </tr>
      </thead>
      <tbody>
      <% @products.each do |product| %>
          <tr>
            <td>
              <%= image_tag('http://placehold.it/90x90', :class => 'thumbnail') %>
            </td>
            <td>
              <dl>
                <dt><%= product.title %></dt>
                <dd>
                  <%= truncate(strip_tags(product.description), :length => 80) %>
                </dd>
              </dl>
            </td>
            <td><%= product.price %> </td>
            <td>
              <a href="#" class="label" data-controls-modal="modal-form-<%= @formName %>" data-backdrop="false"
                 onclick="$('#products-form').html(' ').load('<%= product_path(product) %>');"> Show </a> |
              <a href="#" class="label notice" data-controls-modal="modal-form-<%= @formName %>" data-backdrop="false"
                 onclick="$('#products-form').html(' ').load('<%= edit_product_path(product)%>');"> Edit </a> |
              <%= link_to 'Delete', product, :confirm => 'Are you sure?', :method => :delete, :class => 'label warning' %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<%= render :partial => "shared/tbar" %>
<div class="container padding-top60">
  <% flash.each do |name, message| %>
      <div class="alert-message success fade in">
        <a class="close" href="#">&times;</a>

        <p><strong>Success!</strong> <%= notice %> </p>
      </div>
  <% end %>
  <div id="content" class="content">

    <%= render :partial => "products/modal_form" %>

    <%= form_tag products_path, :method => 'get', :id => "products_search" do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>

        <div id="products"><%= render 'products' %></div>
    <% end %>

  </div>
  <%= render :partial => "shared/footer" %>
</div>

app/views/products/index.js.erb
$("#products").html("<%= escape_javascript(render("products")) %>");

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= render :partial => "products/product_tpl" %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/shared/_footer.html.erb
<footer>
    <p>&copy; Company 2011</p>
</footer>

app/views/shared/_header.html.erb
<div class="topbar">
  <div class="fill">
    <div class="container">
      <a class="brand" href="/">Manduks Depot</a>
      <ul class="nav">
        <li class="active"><a href="/">Store</a></li>
        <li><a href="/products">Products</a></li>
        <li><a href="/orders">Orders</a></li>
        <% unless @cart.line_items.empty? %>
            <li>
              <a class='' data-controls-modal="modal-cart" data-backdrop="true" data-keyboard="true"
                 onclick="$('#cart-list').load('/carts/<%= session[:cart_id]%>')">
                <span class="label notice">Cart</span>
              </a>
            </li>
        <% end %>
      </ul>
      <form action="" class="pull-right">
        <input class="input-small" type="text" placeholder="Username">
        <input class="input-small" type="password" placeholder="Password">
        <button class="btn" type="submit">Sign in</button>
      </form>
    </div>
  </div>
</div>

app/views/shared/_main.html.erb
<%= render 'tbar' %>
<div class="container padding-top60">
  <% flash.each do |name, message| %>
      <div class="alert-message success fade in">
        <a class="close" href="#">&times;</a>
        <p><strong>Success!</strong> <%= notice %> </p>
      </div>
  <% end %>
  <div id="content" class="content"></div>
  <%= render 'footer' %>
</div>

app/views/shared/_tbar.html.erb
<div class="topbar">
  <div class="fill">
    <div class="container">
      <a class="brand" href="/">Depot</a>
      <ul class="nav">
        <li class="active"><a href="/">Store</a></li>
        <li><a href="/products">Products</a></li>
        <li><a href="/orders">Orders</a></li>

      </ul>
      <form action="" class="pull-right">
        <input class="input-small" type="text" placeholder="Username">
        <input class="input-small" type="password" placeholder="Password">
        <button class="btn" type="submit">Sign in</button>
      </form>
    </div>
  </div>
</div>